defaults: &defaults
    docker:
        - image: circleci/node:8.10.0
    working_directory: ~/tmp/circlci-now

version: 2
jobs:
    checkout:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                at: ~/tmp/circlci-now
            - restore_cache:
                keys:
                    - npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
                    - npm-cache-{{ .Branch }}
                    - npm-cache-
            - run:
                name: NPM Install
                command: npm install
            - save_cache:
                key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - persist_to_workspace:
                root: .
                paths: .
    unit-test:
        <<: *defaults
        steps:
            - attach_workspace:
                at: ~/tmp/circlci-now
            - run:
                name: NPM Install
                command: npm install
            - run:
                name: Unit Test
                command: npm run test
workflows:
    version: 2
    test:
        jobs:
            - checkout
            - unit-test:
                requires:
                    - checkout
